# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.0.post23+g2da383c.d20220713'
__version_tuple__ = version_tuple = (0, 0, 'g2da383c.d20220713')
